data<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
subdata<-subset(data,data$Date=="1/2/2007" | data$Date=="2/2/2007")
datetime<-strptime(paste(subdata$Date,subdata$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(datetime,as.numeric(subdata$Global_active_power),type="l",xlab="",ylab="Global Active Power")
plot(datetime, as.numeric(subdata$Voltage),type="l",xlab="",ylab="Voltage")
plot(datetime,as.numeric(subdata$Sub_metering_1),type="l",xlab="",ylab="Energy Submetering")
lines(datetime,as.numeric(subdata$Sub_metering_2),type="l",col="red")
lines(datetime,as.numeric(subdata$Sub_metering_3),type="l",col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2, col=c("black", "red", "blue")) 
plot(datetime, as.numeric(subdata$Global_reactive_power), type="l", xlab="datetime", ylab="Global Reactive Power")
dev.off()